apiVersion: apps/v1
kind: Deployment
metadata:
  name: configs-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: configs-db
  template:
    metadata:
      labels:
        name: configs-db
      annotations:
        prometheus.io.scrape: "false"
    spec:
      containers:
      - name: configs-db
        image: postgres:9.6
        env:
          - name: POSTGRES_DB
            value: configs
        ports:
        - containerPort: 5432
      imagePullSecrets:
      - name: {{ .Values.server.dockerSecret }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}

