# Default values for GeckoOnprem.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

server:
  release: 1.1.0-ee
  dockerSecret: geckoonprem-registry-secret
  protocol: http
  url:
  httpNodePort: 30380
  httpsNodePort: 30381
  apiAuthAccessMode: unrestricted
  serverDefaultAccessGrant: true
  apiUiEnabled: true
  setupName: geckoonprem
  apiAuthExternalProviderEnabled: false
  apiAuthExternalProviderConfigured:
  apiAuthInternalProviderEnabled: true
  apiAuthInternalProviderConfigured: localAuthConfig
  apiAuthEnabler:
  apiAuthGithubClientId:
  apiAuthGithubClientSecret:
  apiAuthGoogleClientId:
  apiAuthGoogleClientSecret:
  clusterDomain: cluster.local
  featureSubscriptionDisable: false
  subscriptionType: internal
  featureBillingDisable: true
  billingType: external
  featureEmailDisable: true
  senderEmailAddress:
  senderEmailPassword:
  featureDocsDisable: false
  docsUrl: https://docs.mayaonline.io
  featureChatBotDisable: true
  slackConfigBotClientId:
  slackConfigBotClientSecret:
  slackNotificationWelcomeMessage:
  featureKialiDisable: true
  analyticsGoogleCode:
  autoconnectLocalCluster: true

mysql:
  storageClass: standard
  storageCapacity: 50Gi

elasticSearch:
  storageClass: standard
  storageCapacity: 50Gi
  replicas: 1

cassandra:
  storageClass: standard
  storageCapacity: 50Gi
  replicas: 1

mayaStore:
  storageClass: standard
  storageCapacity: 10Gi

grafana:
  storageClass: standard
  storageCapacity: 50Gi

cortex:
  replicationFactor: 1
  timeout: 5s

alertStore:
  replicationFactor: 1

ingester:
  replicas: 1

querier:
  replicas: 1


